apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: posts-app
spec:
  rules:
  - http:
      paths:
      - path: /posts
        pathType: Prefix
        backend:
          service:
            name: posts-service
            port: 
              number: 3000